class PropertyModel {
  constructor(pool) {
    this.pool = pool;
  }

  async create(data) {
    const { 
      // id is usually generated by DB (uuid_generate_v4()) or backend. 
      // Assuming DB default or passed in. Let's assume passed in or DB default.
      // Based on AuthController, we might be generating UUIDs in backend, but node-pg-migrate validation ensures DB can too.
      // sticking to backend generation if consistency is needed, 
      // but standard is usually DB default. AuthController manually gen'd UID.
      // I'll assume caller provides ID or it's auto-generated.
      // Let's support passing keys.
      id, user_id, title, type, location, price, description, status, image_url, facilities, developer_info 
    } = data;

    const result = await this.pool.query(
      `INSERT INTO properties (
        id, user_id, title, type, location, price, description, status, image_url, facilities, developer_info, created_at, updated_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
      RETURNING *`,
      [id, user_id, title, type, location, price, description, status || 'active', image_url, facilities, developer_info]
    );
    return result.rows[0];
  }

  async findAll(filters = {}, limit = 20, offset = 0) {
    // Basic implementation, can be expanded with WHERE clauses based on filters
    let query = 'SELECT * FROM properties';
    const params = [];
    const whereClauses = [];

    if (filters.user_id) {
      params.push(filters.user_id);
      whereClauses.push(`user_id = $${params.length}`);
    }
    
    if (filters.status) {
      params.push(filters.status);
      whereClauses.push(`status = $${params.length}`);
    }

    if (whereClauses.length > 0) {
      query += ' WHERE ' + whereClauses.join(' AND ');
    }

    query += ` ORDER BY created_at DESC LIMIT $${params.length + 1} OFFSET $${params.length + 2}`;
    params.push(limit, offset);

    const result = await this.pool.query(query, params);
    return result.rows;
  }

  async findById(id) {
    const result = await this.pool.query('SELECT * FROM properties WHERE id = $1', [id]);
    return result.rows[0];
  }

  async update(id, data) {
    // Dynamic update
    const keys = Object.keys(data).filter(k => k !== 'id' && k !== 'created_at');
    if (keys.length === 0) return null;

    const setClause = keys.map((k, i) => `${k} = $${i + 2}`).join(', ');
    const values = keys.map(k => data[k]);
    
    const result = await this.pool.query(
      `UPDATE properties SET ${setClause}, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING *`,
      [id, ...values]
    );
    return result.rows[0];
  }

  async delete(id) {
    await this.pool.query('DELETE FROM properties WHERE id = $1', [id]);
  }
}

module.exports = PropertyModel;
